baseURL = 'https://www.mainesec.org/'
languageCode = 'en-us'
title = 'MaineSec'
theme = "terminal"
#enableInlineShortcodes = true

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "MaineSec"
    subtitle = ""
    keywords = "maine hacking security local meetup"
    copyright = "2022"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "MaineSec"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "Discord"
        name = "Join the Chat on Discord"
        url = "https://discord.mainesec.org"

