baseURL = 'http://mainesec.org/'
languageCode = 'en-us'
title = 'MaineSec'
theme = "terminal"
#enableInlineShortcodes = true

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false

[languages]
  [languages.en]
    title = "Terminal"
    subtitle = "A simple, retro theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "MaineSec"
      logoHomeLink = "/"

